name: ds
channels:
  - defaults  
dependencies:
  - python=3.8.5
  - numpy
  - pandas  
  - scikit-learn
  - pyyaml
  - seaborn
  - matplotlib
  - scipy
  - lightgbm
  - future
  - jupyter=1.0.0
  - pip



